updated test.yml to remove birthdays.csv requirement.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -63,12 +63,12 @@ jobs:
             exit 1
           fi
 
-          if [ -f "birthdays.csv" ]; then
-            echo "birthdays.csv found"
-          else
-            echo "birthdays.csv not found!"
-            exit 1
-          fi
+          # if [ -f "birthdays.csv" ]; then
+          #   echo "birthdays.csv found"
+          # else
+          #   echo "birthdays.csv not found!"
+          #   exit 1
+          # fi
 
           echo ""
           echo "All required files found!"
